### ISSUE TITLE
About input files

### ISSUE THREAD

**Issue by jktms** [utlive/VideoBLIINDS#1]
Can i have a reference？Regarding 'frames.mat', 'features_test.txt',‘ predicted_dmos.txt’， what should the input format of these files look like？

**Comment by JoshuaEbenezer** [comment]
Hi @jktms 
'frames.mat' should have a luma (grayscale) video of dimensions "height x width x no. of frames". 'features_test.txt' should be a file that contains the saved 'features_test' variable. 'predicted_dmos.txt' is actually irrelevant. It's only used to save the predictions.

I would recommend using https://github.com/pavancm/vbliinds if you want to have a faster python implementation.

Regards,
Josh

**Comment by jktms** [comment]
got it thanks
